 services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "4040:4040"
    networks:
      - desafiodocker
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - desafiodocker
 networks:
  desafiodocker:
    driver: bridge
